name: first workflow

on:
  workflow_dispatch

jobs:
  firstJob:
    runs-on: self-hosted
    # run-on: ubuntu-latest
    steps: 
    - name: first Job step script
      shell: cmd
      run: echo Hello-World! This is the first job
  secondJob: 
    runs-on: ubuntu-latest
    steps:
    - name: second step script
      shell: bash
      run: |
        echo 'This is the second step in first job'
        echo 'From second step'
