name: first workflow

on:
  workflow_dispatch

jobs:
  firstJob:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps: 
    - name: first Job step script
      shell: bash
      run: echo Hello-World! This is the first job
    - name: checkout
      uses: actions/checkout@v3.5.3
    - name: greetings
      id: geetings
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
    - name: time
      run: |
        echo "The time of the greeting was at: ${{ steps.geetings.outputs.time }}"
    - name: environment variables
      env:
        STEP_VAR: "This  var is declared to be at the step level"
      run: |
        echo $WORKFLOW_VAR
        echo $JOB_VAR
        echo $STEP_VAR
        echo "This following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it woundn't be a secret"
        echo $GITHUB_ACTOR
        echo $GITHUB_JOB
        echo $GITHUB_REF
  secondJob: 
    runs-on: ubuntu-latest
    steps:
    - name: second step script
      shell: bash
      run: |
        echo 'This is the second step in first job'
        echo 'From second step'
