name: first workflow

on:
  workflow_dispatch

jobs:
  firstJob:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps: 
    - name: first Job step script
      shell: bash
      run: echo Hello-World! This is the first job
    - name: checkout
      uses: actions/checkout@v3.5.3
    - name: greetings
      id: geetings
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
    - name: time
      run: |
        echo "The time of the greeting was at: ${{ steps.greetings.output.time }}"
  secondJob: 
    runs-on: ubuntu-latest
    steps:
    - name: second step script
      shell: bash
      run: |
        echo 'This is the second step in first job'
        echo 'From second step'
